package my.test.package;

/* Generated by confluent 0.0.1 (https://pypi.org/project/confluent/). */
public class TestConfig {
    public final static boolean MY_BOOLEAN = true;
    public final static int MY_INTEGER = 142;
    public final static float MY_FLOAT = 322.0f;
    public final static double MY_DOUBLE = 233.9d;
    public final static String MY_REGEX = "Test Reg(E|e)x"; /* Just another RegEx. */
    public final static String MY_SUBSTITUTED_STRING = "Sometimes I just want to scream Hello World!";
}
